# Generated by Django 5.2.1 on 2025-05-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='player', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=1000),
        ),
    ]
