# Generated by Django 5.2.1 on 2025-05-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0003_alter_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid'), ('classical', 'Classical')], default='rapid', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='time_control',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='Контроль времени (минуты на партию)'),
        ),
    ]
